[package]

edition = "2018"
name = "compiler"
version = "0.0.1"

[[bin]]

name = "compiler"

[dependencies]
ansi_term = "0.11"
byteorder = "1.3.1"
argparse = "0.2.2"
rayon = "1.5.0"
took = "0.1.2"
backtrace = "0.3.56"
